arb-dir: lib/l10n
output-dir: lib/l10n
output-localization-file: app_localizations.dart
untranslated-messages-file: lib/l10n/untranslated.json
template-arb-file: intl_en.arb
output-class: AppLocalizations
preferred-supported-locales:
  - en
  - ja
